### PR TITLE
Implement the ability to write the console output of processes into a file

### PR DESCRIPTION
**Pull request by nj0yeh**
Implement the ability to write the console output of processes into a file

Usage: Add path to .yaml file in parameter `consoleLogDestinationPath`. Can contain environment variables.

The same file can be reused for multiple processes.

### CODE REVIEW

**Comment by davidfowl** [comment]
Why do I want this?

**Comment by sheryever** [comment]
Powershell can write the output in file

**Comment by nj0yeh** [comment]
To start processes via bash and parse the logs to determine the correct times to trigger something (e. g. a call to a web route inside the processes).
Second usage is to store the logs in artifact in the CI system when something fails.

**Comment by davidfowl** [comment]
@nj0yeh How are you using this on a CI machine? I don't understand the scenario so help me a bit here.

**Comment by nj0yeh** [comment]
We use it as replacement for a Kubernetes environment. In an integration test, we run multiple processes and simulate different scenarios by sending web requests to the processes. When something fails, we need the logs (that are written to stdout and stderr) of all processes to analyze the error.

**Comment by nj0yeh** [comment]
This PR is the replacement for the `kubectl logs` command.

**Comment by davidfowl** [comment]
OK I *think* understand the scenario but I'm not a fan of this implementation. It also doesn't support the docker at the moment. Can you open an issue for this feature?

**Comment by nj0yeh** [comment]
It does support Docker. But I can open an issue for this as well.

**Pull request closed without merging**
